---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  profile:
    displayName: Guests
  children: []
---
# Example Microsoft user that would be created by the Microsoft Graph provider
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: "example.user"
  annotations:
    microsoft.com/email: "example.user@yourdomain.com"
    microsoft.com/objectId: "00000000-0000-0000-0000-000000000000"
spec:
  profile:
    displayName: "Example User"
    email: "example.user@yourdomain.com"
  memberOf: [everyone]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: everyone
spec:
  type: team
  profile:
    displayName: Everyone
  children: []